### ISSUE TITLE
Responsive Design Testing

### ISSUE THREAD

**Issue by HarishT-dev** [HarishT-dev/harish.github.io#1]
I am working on the responsive website which deals with the different types of maintenance services. It has an issue with the responsiveness as it doesn't work in Tab & Mobile. 
![highsky](https://user-images.githubusercontent.com/72560242/95621992-3ffc4d80-0a90-11eb-874d-ab361993b350.PNG)

**Comment by ashisharvindthakre** [comment]
As I was going through your webpage, found a few issues;

1. The JS query is missing in order to make it responsive. 
2. I see that there is a Search icon on the top but it doesn't work as I am unable to enter the data as no search box.
3. There is also an issue with the styling.

Can you please assign this issue to me?

**Comment by raokshitij** [comment]
Can you please assign this work to me?

**Comment by hypecolonel** [comment]
I would like to work on this project. Looking forward for your response.

**Comment by HarishT-dev** [comment]
@ashisharvindthakre go for it

**Comment by HarishT-dev** [comment]
This issue has been resolved. Page is responsive and search bar works fine with accordion. I’m closing the issue.
